version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab-ce
    restart: always
    hostname: 'gitlab.example.com' # Reemplaza con tu nombre de dominio
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com' # Reemplaza con tu URL externa
        gitlab_rails['gitlab_shell_ssh_port'] = 2222 # Puerto SSH
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'

# Reemplazar los marcadores de posición:
# gitlab.example.com con el nombre de dominio para acceder.
# https://gitlab.example.com con la URL externa.
# $GITLAB_HOME con la ruta a un directorio del host local.
# Crea el directorio $GITLAB_HOME:
# mkdir -p $GITLAB_HOME/config $GITLAB_HOME/logs $GITLAB_HOME/data
