apiVersion: v1
kind: Pod
metadata:
  name: pytorch-pod
spec:
  containers:
    - name: pytorch
      image: pytorch/pytorch:latest  # La imagen base tiene Python y PyTorch
      ports:
        - containerPort: 8888
      command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
      volumeMounts:
        - mountPath: /mnt/shared
          name: shared-volume
      workingDir: /mnt/shared
  volumes:
    - name: shared-volume
      hostPath:
        path: /Users/ivan/Desktop/DataConteiners
        type: Directory
