services:
  spark-master:
    image: apache/spark:latest
    ports:
      - "7077:7077" # Puerto para la comunicación entre workers y master
      - "8080:8080" # Interfaz web de Spark Master
    environment:
      SPARK_MODE: master
    volumes:
      - ./data:/opt/spark/data # Opcional: monta un volumen para tus datos

  spark-worker-1:
    image: apache/spark:latest
    depends_on:
      - spark-master
    ports:
      - "8081:8081" # Interfaz web del worker
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - ./data:/opt/spark/data # Opcional: monta un volumen para tus datos

  spark-worker-2:
    image: apache/spark:latest
    depends_on:
      - spark-master
    ports:
      - "8082:8082" # Interfaz web del worker
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - ./data:/opt/spark/data # Opcional: monta un volumen para tus datos
