services:
  metadata_db:
    image: postgres:16
    container_name: metadata_db
    restart: always
    environment:
      POSTGRES_USER: openmetadata_user
      POSTGRES_PASSWORD: openmetadata_pass
      POSTGRES_DB: openmetadata_db
    volumes:
      - metadata_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  opensearch:
    image: opensearchproject/opensearch:2.5.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  openmetadata:
    image: openmetadata/server:latest
    container_name: openmetadata
    restart: always
    depends_on:
      - metadata_db
      - opensearch
    environment:
      OM_DATABASE_HOST: metadata_db
      OM_DATABASE_PORT: 5432
      OM_DATABASE_USER: openmetadata_user
      OM_DATABASE_PASSWORD: openmetadata_pass
      OM_DATABASE_NAME: openmetadata_db
      OM_SEARCH_TYPE: opensearch
      OM_SEARCH_HOST: http://opensearch:9200
    ports:
      - "8585:8585"
    volumes:
      - openmetadata_data:/openmetadata_data

volumes:
  metadata_db_data:
  opensearch_data:
  openmetadata_data:
