services:
  trino:
    image: trinodb/trino:latest
    container_name: trino
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TRINO_MEMORY_MAX=4GB
    volumes:
      - ./trino-config:/etc/trino
    networks:
      - trino-network

networks:
  trino-network:
    driver: bridge
