version: '3.8'
services:
  trino:
    image: docker.io/trinodb/trino
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - "trino-config:/etc/trino/catalog"
    restart: unless-stopped
volumes:
  trino-config:
