# Cesar Omar Martin Rodriguez
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana_data:/var/lib/grafana  # Carpeta local para persistencia
    networks:
      - grafana_network

# Ya no usamos volumes: grafana_data, porque montamos una carpeta local

networks:
  grafana_network:
    driver: bridge
