# Componente Superset
version: "3.7"

services:

  superset:
    build:
      context: ./services/superset
    image: superset:trino
    ports: 
      - 8090:8080
    container_name: superset
    volumes: 
      - superset_vol:/app/superset_home

networks:
  default:
    driver: bridge
    name: lagodedatosnetwork

volumes:
  superset_vol:
